<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Delete student');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['student_no']) && isset($_GET['Interviewee_interview_no']) && isset($_GET['Interviewee_Exam_exam_no']) && isset($_GET['Interviewee_Exam_Applicant_applicant_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/student.php';
    $dbh_student = new student;
    $dbh_student->set_where("student_no='$student_no' AND Interviewee_interview_no='$Interviewee_interview_no' AND Interviewee_Exam_exam_no='$Interviewee_Exam_exam_no' AND Interviewee_Exam_Applicant_applicant_no='$Interviewee_Exam_Applicant_applicant_no'");
    if($result = $dbh_student->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_student.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    elseif($_POST['delete'])
    {
        log_action('Pressed delete button', $_SERVER[PHP_SELF]);
        require_once 'subclasses/student.php';
        require_once 'validation_class.php';
        $dbh_student = new student;
        $validator = new validation;

        $dbh_student->del($_POST);


        header("location: listview_student.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }
}
require_once 'subclasses/student_html.php';
$html = new student_html;
$html->draw_header('Delete student', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo "<input type=hidden name='student_no' value='$student_no'>";
echo "<input type=hidden name='Interviewee_interview_no' value='$Interviewee_interview_no'>";
echo "<input type=hidden name='Interviewee_Exam_exam_no' value='$Interviewee_Exam_exam_no'>";
echo "<input type=hidden name='Interviewee_Exam_Applicant_applicant_no' value='$Interviewee_Exam_Applicant_applicant_no'>";

$html->detail_view = TRUE;

$html->draw_controls('delete');

$html->draw_footer();