<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Edit student');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['student_no']) && isset($_GET['Interviewee_interview_no']) && isset($_GET['Interviewee_Exam_exam_no']) && isset($_GET['Interviewee_Exam_Applicant_applicant_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/student.php';
    $dbh_student = new student;
    $dbh_student->set_where("student_no='$student_no' AND Interviewee_interview_no='$Interviewee_interview_no' AND Interviewee_Exam_exam_no='$Interviewee_Exam_exam_no' AND Interviewee_Exam_Applicant_applicant_no='$Interviewee_Exam_Applicant_applicant_no'");
    if($result = $dbh_student->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);
        $orig_student_no = $student_no;
        $orig_Interviewee_interview_no = $Interviewee_interview_no;
        $orig_Interviewee_Exam_exam_no = $Interviewee_Exam_exam_no;
        $orig_Interviewee_Exam_Applicant_applicant_no = $Interviewee_Exam_Applicant_applicant_no;

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_student.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    if($_POST['submit'])
    {
        log_action('Pressed submit button', $_SERVER[PHP_SELF]);


        require_once 'validation_class.php';
        require_once 'subclasses/student.php';
        $dbh_student = new student;
        $validator = new validation;

        $message .= $dbh_student->sanitize($_POST);
        extract($_POST);

        if($dbh_student->check_uniqueness_for_editing($_POST)) ;
        else $message = "Record already exists with the same primary identifiers!";

        if($message=="")
        {
            $dbh_student->edit($_POST);


            header("location: listview_student.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
        }
    }
}
require_once 'subclasses/student_html.php';
$html = new student_html;
$html->draw_header('Edit student', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo "<input type=hidden name='orig_student_no' value='$orig_student_no'>";
echo "<input type=hidden name='orig_Interviewee_interview_no' value='$orig_Interviewee_interview_no'>";
echo "<input type=hidden name='orig_Interviewee_Exam_exam_no' value='$orig_Interviewee_Exam_exam_no'>";
echo "<input type=hidden name='orig_Interviewee_Exam_Applicant_applicant_no' value='$orig_Interviewee_Exam_Applicant_applicant_no'>";

$html->draw_controls('edit');

$html->draw_footer();