<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Add user role');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['filter_used']) && isset($_GET['page_from']) && isset($_GET['role_id']))
{
    extract($_GET);

    //Get Role Name
    require_once 'subclasses/user_role.php';
    $obj_role = new user_role;
    $obj_role->get_role_name($role_id);
    $role = $obj_role->role;
    
    //Get existing role permissions
    require_once 'subclasses/user_role_links.php';
    $obj_role = new user_role_links;
    $obj_role->get_user_role_links($role_id);
    $num_permissions = $obj_role->num_rows;
    $module = $obj_role->arr_link;
}

if(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_user_role.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    if($_POST['submit'])
    {
        log_action('Pressed submit button', $_SERVER[PHP_SELF]);
        extract($_POST);        

        require_once 'subclasses/user_role_links.php';
        $obj_role = new user_role_links;
        $obj_role->del($role_id);
            
        for($a=0; $a<$permissions_count; $a++)
        {
            if($module[$a] != '')
            {
                $param = array('role_id'=>$role_id,
                               'link_id'=>$module[$a]);
                $obj_role->add($param);
            }
        }
        $obj_role->close_db();
        header("location: listview_user_role.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }
}
require_once 'subclasses/user_role_html.php';
$html = new user_role_html;
$html->draw_header('Role Permissions', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo '<div class="container_mid">
    <fieldset class="top"> Define Permissions for Role: ' . $role . '</fieldset>
    <fieldset class="middle">
    <table class="input_form">';

echo '<input type="hidden" name="role" value="' . $role . '">';
echo '<input type="hidden" name="role_id" value="' . $role_id . '">';

$html->draw_text_field('Role','role',TRUE);

$query = "SELECT link_id, descriptive_title FROM `user_links` ORDER BY descriptive_title";
$value = 'link_id';
$items = array('descriptive_title');
$multifield_params = array(
                         'field_labels' => array('Module'),
                         'field_controls' => array('draw_select_field_from_query_mf'),
                         'field_parameters' => array(
                                                    array($query, $value, $items, 'module')
                                                    )
                        );
$html->draw_multifield_auto('Permissions', $multifield_params, 'num_permissions', 'permissions_count');

echo '</table>
    </fieldset>
    <fieldset class="bottom">';

$html->draw_submit_cancel();
echo '</fieldset>';
echo '</div>';

$html->draw_footer();
