<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Set User Passports');

if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);
 
if ($_GET['Username'] != "")
{
    $Username = $_GET['Username'];
    $fromSuccess="YES";
}

if(xsrf_guard())
{
    
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header('location: ' . HOME_PAGE);
        exit();
    }
    
    extract($_POST);
        
    if(($_POST['find']) || ($_POST['passportButton']) || ($fromSuccess=="YES"))
    {
        $data_con = new data_abstraction;
        $data_con->set_fields('a.person_id, b.user_type, c.first_name, c.middle_name, c.last_name');
        $data_con->set_table('user a, user_types b, person c');
        $data_con->set_where("a.username='$Username' AND a.user_type_id = b.user_type_id AND a.person_id = c.person_id");
        $result = $data_con->make_query();
        $numrows = $data_con->num_rows;
        $data_con->close_db();
        
        if($numrows==1)
        {
            $data = $result->fetch_assoc();
            extract($data);
            $Name = $first_name . ' ' . $middle_name . ' ' . $last_name;
            $Type = $user_type;
        }
        elseif($numrows==0) 
        {
            $message = 'No match found for username you entered.';
            $message_type = 'error';
            $_POST['passportButton'] = FALSE;
            $_POST['find'] = FALSE;
            $Name="";
            $Type="";
        }
    }
    
    if($_POST['submit'])
    {
        $link = $_POST['link'];

        if($passportGroup!="All Groups")
        {
            $data_con = new data_abstraction;
            $data_con->set_fields('link_id');
            $data_con->set_table('user_links');
            $data_con->set_where("passport_group_id='$passportGroup'");
            $result = $data_con->make_query();
            $numrows = $data_con->num_rows;
            $data_con->close_db();
            if($numrows>0)
            {
                for($a=0;$a<$numrows;$a++)
                {
                    $info=$result->fetch_row();
                    if($a != ($numrows - 1)) $completeList = $completeList . "'$info[0]',";
                    else $completeList = $completeList . "'$info[0]'";
                }
                
                $data_con = new data_abstraction;
                $data_con->set_query_type('DELETE');
                $data_con->set_table('user_passport');
                $data_con->set_where("username='$Username' AND link_id IN ($completeList)");
                $data_con->make_query();
                $data_con->close_db();
            }
        }
        else
        {
            $data_con = new data_abstraction;
            $data_con->set_query_type('DELETE');
            $data_con->set_table('user_passport');
            $data_con->set_where("username='$Username'");
            $data_con->make_query();
            $data_con->close_db();
        }

        //FIXME: Make this a batch insert instead of a looped single insert.
        for($a=0;$a<$numLinks;$a++)
        {
            if($link[$a])
            {
                $data_con = new data_abstraction;
                $data_con->set_query_type('INSERT');
                $data_con->set_table('user_passport');
                $data_con->set_fields('username, link_id');
                $data_con->set_values("'$Username', '$link[$a]'");
                $data_con->make_query();
                $data_con->close_db();
            }
        }
        $message = 'Passport settings succesfully updated';
        $message_type = 'system';
    }
}
$html_writer = new html;
$html_writer->draw_header('Set User Passports', $message, $message_type);
?>
<div class="container_mid_huge2">
<fieldset class="top"> Modify the System Privileges of Users</fieldset>
<fieldset class="middle">
<table class="input_form" width="900">
<tr><td>[Set Permissions Per User] :: <a class="listview" href="set_user_passports2.php">[View and Remove Permissions Per Module]</a> :: <a class="listview" href="set_user_passports3.php">[Role-Based Access Control Interface]</a><hr></td>
</table>
<table width=75% border=0 cellpadding=2 cellspacing=2 align=center class=tableContent>
<TR><TD align=right> Username: </TD><TD colspan=3><input type=text name="Username" value="<?php echo $Username; ?>"> <input type=submit name=find value="FIND" class=button1></TD></TR>
<TR><TD align=right> Full Name: </TD><TD><input type=text name="Name" size=30 value="<?php echo $Name; ?>" readonly></TD>
    <TD align=right> User Type: </TD><TD><input type=text name="Type" value="<?php echo $Type; ?>" readonly></TD></TR>
<TR><TD align=right> Passport Group: </TD><TD colspan=3>
    <SELECT NAME=passportGroup>
    <?php
    echo '<option selected>All Groups</option>';
    $data_con = new data_abstraction;
    $data_con->connect_db();
    $data_con->set_fields('passport_group_id, passport_group AS Passport_Group_Name');
    $data_con->set_table('user_passport_groups');
    $data_con->set_order('passport_group');
    if($result = $data_con->make_query())
    {
        $a=0;
        while($data = $result->fetch_assoc())
        {
            extract($data);
            $selected = '';
            if($passport_group_id == $passportGroup) $selected = 'selected';
            echo "<option value='$passport_group_id' $selected> $Passport_Group_Name </option>";
        }
        $result->close();
    }
    else die($data_con->error);
    $data_con->close_db();
    ?>    
    </SELECT> <input type=submit name="passportButton" value="GO" class=button1>
    </TD>
</TR>
</TABLE>

<table class="input_form" width="900">
<tr><td><hr></td>
</table>

<?php 

if(($_POST['passportButton']) || ($_POST['find']))
{
    if($passportGroup != 'All Groups')
    {    
        $data_con = new data_abstraction;
        $data_con->connect_db();
        $data_con->set_fields('passport_group AS `Group_Title`');
        $data_con->set_table('user_passport_groups');
        $data_con->set_where("passport_group_id = '$passportGroup'");
        $result = $data_con->make_query();
        $data_con->close_db();
        
        $info = $result->fetch_assoc();
        extract($info);
    }
    else $Group_Title = "All Groups";
?>
    <br><br>
    <TABLE WIDTH="900" BORDER=1 class=listView align=center>
    <TR class="listRowHead"><TD colspan=2> <?php echo "$Group_Title passport for $Name";?></TD></TR>
    <TR><TD colspan=2>
        <input type=button name=CHECK value="CHECK ALL" class="button1" onClick="checkAll();">
        <input type=button name=UNCHECK value="UNCHECK ALL" class="button1" onClick="uncheckAll();">
    </TD></TR>
    <?php
    $data_con = new data_abstraction;
    $data_con->set_fields('a.link_id, a.descriptive_title AS `Module_Name`');
    $data_con->set_table('user_links a, user_passport_groups b');
    
    if($passportGroup!="All Groups") 
        $data_con->set_where("a.passport_group_id = b.passport_group_id AND b.passport_group_id='$passportGroup'");
    elseif($passportGroup=="All Groups") 
        $data_con->set_where("a.passport_group_id = b.passport_group_id AND b.passport_group_id!=''");

    $data_con->set_order('a.descriptive_title');
    $result = $data_con->make_query();
    $numrows= $data_con->num_rows;
    $data_con->close_db();
    echo "<input type=hidden name=numLinks value='$numrows'>";

    for ($a=0;$a<$numrows;$a+=2)
    {
        if($a%4==0) $class='listRowEvenNoHighlight';
        else $class='listRowOddNoHighlight';

        $info=$result->fetch_assoc();
        extract($info);
        
        $data_con = new data_abstraction;
        $data_con->set_fields('username');
        $data_con->set_table('user_passport');
        $data_con->set_where("username='$Username' AND link_id='$link_id'");
        $data_con->make_query();

        $checked = '';
        if($data_con->num_rows==1) $checked = 'checked';

        echo "<TR class=$class><TD class=\"listCell\"><label style=\"display: block;\" for='checkfield[$a]'><input type=checkbox ID='checkfield[$a]' name=\"link[]\" value='$link_id' $checked> $Module_Name</label></TD>";

        $data_con->close_db();
        
        if(($a+1) < $numrows)
        {
            $info=$result->fetch_assoc();
            extract($info);

            $data_con = new data_abstraction;
            $data_con->set_fields('username');
            $data_con->set_table('user_passport');
            $data_con->set_where("username='$Username' AND link_id='$link_id'");
            $data_con->make_query();

            if($data_con->num_rows==0)     echo "<TD class='listCell'><label style=\"display: block;\" for=\"checkfield[" . ($a+1) . "]\"><input type=checkbox ID='checkfield[" . ($a+1) . "]' name=\"link[]\" value='$link_id'> $Module_Name</label></TD></TR>";
            elseif($data_con->num_rows==1) echo "<TD class='listCell'><label style=\"display: block;\" for=\"checkfield[" . ($a+1) . "]\"><input type=checkbox ID='checkfield[" . ($a+1) . "]' name=\"link[]\" value='$link_id' checked> $Module_Name</label></TD></TR>";

            $data_con->close_db();
        }
        else echo "<TD class='listCell'> &nbsp; </TD></TR>";
    }
    if($numrows > 0)
    {
        echo "<TR><TD colspan=2 align=center>
                Submit new $Group_Title passport settings for $Name <BR>
                <input type=submit name=submit value='SUBMIT' class=submit>
                <input type=submit name=cancel value='CANCEL' class=cancel>";
    }
    else 
    {
        echo "<TR><TD colspan=2> No modules found for this passport group. Please choose a different passport group.";
    }    
    ?>
    </TD></TR>
    </TABLE>

<?php 
} 
else echo "<TABLE align=center><TR><TD><input type=submit name=cancel value='CANCEL' class=button1></TD></TR></TABLE>";
echo '</fieldset>';
echo '</div>';
$html_writer->draw_footer();
?>
<script language="JavaScript" type="text/JavaScript">
function checkAll()
{

    var arrCheckBoxes = document.getElementsByName('link[]');
    for (var i = 0; i < arrCheckBoxes.length; i++)
    {
        arrCheckBoxes[i].checked = true;
    }
}
function uncheckAll()
{
    var arrCheckBoxes = document.getElementsByName('link[]');
    for (var i = 0; i < arrCheckBoxes.length; i++)
    {
        arrCheckBoxes[i].checked = false;
    }
}
</script>
<?php
