<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Delete studentsection');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['Student_student_no']) && isset($_GET['Section_section_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/studentsection.php';
    $dbh_studentsection = new studentsection;
    $dbh_studentsection->set_where("Student_student_no='$Student_student_no' AND Section_section_no='$Section_section_no'");
    if($result = $dbh_studentsection->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_studentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    elseif($_POST['delete'])
    {
        log_action('Pressed delete button', $_SERVER[PHP_SELF]);
        require_once 'subclasses/studentsection.php';
        require_once 'validation_class.php';
        $dbh_studentsection = new studentsection;
        $validator = new validation;

        $dbh_studentsection->del($_POST);


        header("location: listview_studentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }
}
require_once 'subclasses/studentsection_html.php';
$html = new studentsection_html;
$html->draw_header('Delete studentsection', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo "<input type=hidden name='Student_student_no' value='$Student_student_no'>";
echo "<input type=hidden name='Section_section_no' value='$Section_section_no'>";

$html->detail_view = TRUE;

$html->draw_controls('delete');

$html->draw_footer();