<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Edit studentsection');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['Student_student_no']) && isset($_GET['Section_section_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/studentsection.php';
    $dbh_studentsection = new studentsection;
    $dbh_studentsection->set_where("Student_student_no='$Student_student_no' AND Section_section_no='$Section_section_no'");
    if($result = $dbh_studentsection->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);
        $orig_Student_student_no = $Student_student_no;
        $orig_Section_section_no = $Section_section_no;

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_studentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    if($_POST['submit'])
    {
        log_action('Pressed submit button', $_SERVER[PHP_SELF]);


        require_once 'validation_class.php';
        require_once 'subclasses/studentsection.php';
        $dbh_studentsection = new studentsection;
        $validator = new validation;

        $message .= $dbh_studentsection->sanitize($_POST);
        extract($_POST);

        if($dbh_studentsection->check_uniqueness_for_editing($_POST)) ;
        else $message = "Record already exists with the same primary identifiers!";

        if($message=="")
        {
            $dbh_studentsection->edit($_POST);


            header("location: listview_studentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
        }
    }
}
require_once 'subclasses/studentsection_html.php';
$html = new studentsection_html;
$html->draw_header('Edit studentsection', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo "<input type=hidden name='orig_Student_student_no' value='$orig_Student_student_no'>";
echo "<input type=hidden name='orig_Section_section_no' value='$orig_Section_section_no'>";

$html->draw_controls('edit');

$html->draw_footer();