<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Security Monitor');

if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['DateTimeOptions']))
{
    extract($_GET);

    $settings="";
    if($DateTimeOptions=="ViewAll")
    {
        $settings.= "*No date and time range. <BR>";
        $TimeFilter= "1=1";
    }
    else
    {
        $settings.= "*Start search at ". DATE("F d Y, g:i a",$TimeStart)." and end at ". DATE("F d Y, g:i a",$TimeEnd)." <BR>";
        $TimeFilter = "datetime >= '$TimeStart' AND datetime <= '$TimeEnd'";
    }

    if($UserOptions=="ViewAll")
    {
        $settings.="*View all users. <BR>";
        $UserFilter = "1=1";
    }
    else 
    {
        $settings.="*View only user '".$Username."'.<BR>";
        $UserFilter = "user = '$Username'";
    }

    if($ModuleOptions=="ViewAll")
    {
        $settings.="*View all events in all modules. <BR>";
        $ModuleFilter="1=1";
    }
    else
    {
        $settings.="*View only events at module '".$Module."'<BR>";
        $ModuleFilter="module LIKE '%$Module%'";
    }

    if($KeywordSearch=="Off")
    {
        $settings.="*No keywords used to filter results. <BR>";
        $KeywordFilter="1=1";
    }
    else
    {
        $settings.="*Used the following keyword(s) as filter: '".$Keyword."'<BR>";
        $KeywordFilter="action LIKE '%$Keyword%'";
    }

    if($IPAddressOptions=="Off")
    {
        $settings.="*No IP address used to filter results. <BR>";
        $IPAddressFilter="1=1";
    }
    else
    {
        $settings.="*Used the following as IP address filter: '".$IPAddress."'<BR>";
        $IPAddressFilter="ip_address LIKE '%$IPAddress%'";
    }

}

if(xsrf_guard())
{
    if($_POST['cancel']) 
    {
        log_action("Pressed cancel button", $_SERVER['PHP_SELF']);
        header("location: security_monitor.php");
        exit();
    }

    if(isset($_POST['start'])) $start = $_POST['start'];

    extract($_POST);
}
if(!isset($start)) $start=0;

//Pagination ****************************
//->Query to get total number of records.
$data_con = new data_abstraction;
$data_con->set_fields("entry_id, ip_address, user, datetime, action, module");
$data_con->set_table("`system_log`");
$data_con->set_where("$TimeFilter AND $UserFilter AND $ModuleFilter AND $KeywordFilter AND $IPAddressFilter");
$data_con->set_order("entry_id");
if($result = $data_con->make_query())
{
    $total_records = $data_con->num_rows;
}
else die("Error getting log entries: " . $data_con->QUERY);

//-> Now instantiate the pagination class and feed it the necessary information.
require_once 'paged_result_class.php';
$results_per_page = 50;
$pager = new paged_result($total_records, $results_per_page);
$pager->get_page_data($result_pager, $current_page);
$current_page = $pager->current_page;
$data_con->set_limit($pager->offset, $pager->records_per_page);

$html_writer = new html;
$html_writer->draw_header('Security Monitor', $message, $message_type);
require_once '../javascript/submitenter.php';
?>
<fieldset class="container">
<table width="100%" border="0" cellpadding="0" cellspacing="0">
<tr>
<input type=hidden name=TimeFilter value="<?php echo $TimeFilter;?>">
<input type=hidden name=UserFilter value="<?php echo $UserFilter;?>">
<input type=hidden name=ModuleFilter value="<?php echo $ModuleFilter;?>">
<input type=hidden name=KeywordFilter value="<?php echo $KeywordFilter;?>">
<input type=hidden name=IPAddressFilter value="<?php echo $IPAddressFilter;?>">
<input type=hidden name=settings value="<?php echo $settings;?>">

<tr class="listRowOdd">
    <td colspan="2">
        <?php $html_writer->display_info("Monitor Settings:<br />$settings"); ?>
    </td>
</tr>
<tr class="listRowEven">
    <td align=left><?php $html_writer->draw_button('CANCEL'); ?></td>
    <td align=right><?php echo $pager->draw_paged_result('onKeyPress="submitenter(this,event)"'); ?></td>
</tr>
</table>

<table border=1 width=100% class=listView>
<tr class=listRowHead>
    <td>Entry ID</td>
    <td>IP Address</td>
    <td>User</td>
    <td>Timestamp</td>
    <td>Action</td>
    <td>Module</td>
</tr>

<?php
    if($result = $data_con->make_query())
    {
        $numrows = $data_con->num_rows;

        if($numrows == 1) $record = 'record';
        else $record = 'records';

        $a=0;
        while($row = $result->fetch_assoc())
        {
            if($a%2==0) $class='listRowEven';
            else $class='listRowOdd';
            $a++;

            extract($row);
            echo "<tr class=$class><td class=listCell> $entry_id </td><td class=listCell> $ip_address </td><td class=listCell> $user </td><td class=listCell>" . date("l, F d, Y -- h:i:s a", $datetime) ."</td><td class=listCell> $action </td><td class=listCell> $module </td> </tr>\n";
        }
        $result->close();
    }
    else die("Error getting log entries: $data_con->QUERY   " . $data_con->error);
?>
</table>
</FORM>
</fieldset>
<?php $html_writer->draw_footer(); ?>
