<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require 'path.php';
init_cobalt('Set User Passports');

if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);
 
if(xsrf_guard())
{
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header('location: SetUserPassports.php');
        exit();
    }
    
    extract($_POST);
    
    if($Delete)
    {
        if(is_array($check))
        {
            foreach($check as $user)
            {
                $data_con = new data_abstraction;
                $data_con->set_query_type('DELETE');
                $data_con->set_table('user_passport');
                $data_con->set_where("username='$user' AND link_id='$module'");
                $data_con->make_query();
                $data_con->close_db();
            }
        }
        else $message = "Please select at least one user.";
    }
    
    $data_con = new data_abstraction;
    $data_con->set_fields('username');
    $data_con->set_table('user_passport');
    $data_con->set_where("link_id='$module'");
    $data_con->set_order('username');
    if($result = $data_con->make_query())
    {
        $arrUser = array();
        $showUsers=TRUE;
        $numUsers = $data_con->num_rows;
        for($a=0; $a<$numUsers; $a++)
        {
            $data = $result->fetch_assoc();
            extract($data);
            
            $arrUser[] = $username;
        }
    }
}

$html_writer = new html;
$html_writer->draw_header('Set User Passports', $message, $message_type);
?>

<div class="container_mid_huge2">
<fieldset class="top"> View Users Per Module, and Revoke Permissions</fieldset>
<fieldset class="middle">
<table class="input_form" width="900">
<tr><td><a class="listview" href="set_user_passports.php">[Set Permissions Per User]</a> :: [View and Remove Permissions Per Module] :: <a class="listview" href="set_user_passports3.php">[Role-Based Access Control Interface]</a><hr></td>
</table>
<table width=75% border=0 cellpadding=2 cellspacing=2 align=center class=tableContent>
<?php
$query = "SELECT link_id, descriptive_title FROM `user_links` ORDER BY descriptive_title"; 
$value = 'link_id';
$items = array('descriptive_title');
$html_writer->draw_select_field_from_query($query, $value, $items, 'Module','module',FALSE,TRUE,'','onChange="this.form.submit();"');
?>
</table>
<?php
if($showUsers)
{
    echo '<table width=600 border=0 cellpadding=2 cellspacing=2 align=center class="listView">';
    echo '<tr class="listRowHead"><td align="center" width="50">[X]</td> <td> Username </td></tr>';
    for($a=0; $a<$numUsers; $a++)
    {
        if($a%2==0) $class='listRowEven';
        else $class='listRowOdd';
        echo '<tr class="' . $class . '">';
        echo '<td colspan="2">';
        echo '<label style="display: block" for="' . $arrUser[$a] . '">
                <input type="checkbox" id="' . $arrUser[$a] . '" name="check[]" value="' . $arrUser[$a] . '">&nbsp;&nbsp;' . $arrUser[$a] . '</label></td>';
        echo '</tr>';
    }
    $html_writer->draw_button('SPECIAL', 'button1', 'Delete', 'REMOVE ACCESS', TRUE, '2');
    echo '</table>';
}
?>
</form>
</fieldset>
</div>
<?php $html_writer->draw_footer();
