<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Delete teacher has subject');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['Teacher_teacher_no']) && isset($_GET['Teacher_Department_dept_no']) && isset($_GET['Subject_subject_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/teacher_has_subject.php';
    $dbh_teacher_has_subject = new teacher_has_subject;
    $dbh_teacher_has_subject->set_where("Teacher_teacher_no='$Teacher_teacher_no' AND Teacher_Department_dept_no='$Teacher_Department_dept_no' AND Subject_subject_no='$Subject_subject_no'");
    if($result = $dbh_teacher_has_subject->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_teacher_has_subject.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    elseif($_POST['delete'])
    {
        log_action('Pressed delete button', $_SERVER[PHP_SELF]);
        require_once 'subclasses/teacher_has_subject.php';
        require_once 'validation_class.php';
        $dbh_teacher_has_subject = new teacher_has_subject;
        $validator = new validation;

        $dbh_teacher_has_subject->del($_POST);


        header("location: listview_teacher_has_subject.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }
}
require_once 'subclasses/teacher_has_subject_html.php';
$html = new teacher_has_subject_html;
$html->draw_header('Delete teacher has subject', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo "<input type=hidden name='Teacher_teacher_no' value='$Teacher_teacher_no'>";
echo "<input type=hidden name='Teacher_Department_dept_no' value='$Teacher_Department_dept_no'>";
echo "<input type=hidden name='Subject_subject_no' value='$Subject_subject_no'>";

$html->detail_view = TRUE;

$html->draw_controls('delete');

$html->draw_footer();