<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('View subjectstudentsection');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['Subject_subject_no']) && isset($_GET['StudentSection_Student_student_no']) && isset($_GET['StudentSection_Section_section_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/subjectstudentsection.php';
    $dbh_subjectstudentsection = new subjectstudentsection;
    $dbh_subjectstudentsection->set_where("Subject_subject_no='$Subject_subject_no' AND StudentSection_Student_student_no='$StudentSection_Student_student_no' AND StudentSection_Section_section_no='$StudentSection_Section_section_no'");
    if($result = $dbh_subjectstudentsection->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_subjectstudentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }
}
require_once 'subclasses/subjectstudentsection_html.php';
$html = new subjectstudentsection_html;
$html->draw_header('Detail View: subjectstudentsection', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);
$html->detail_view = TRUE;

$html->draw_controls('view');

$html->draw_footer();