<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Edit subjectstudentsection');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['Subject_subject_no']) && isset($_GET['StudentSection_Student_student_no']) && isset($_GET['StudentSection_Section_section_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/subjectstudentsection.php';
    $dbh_subjectstudentsection = new subjectstudentsection;
    $dbh_subjectstudentsection->set_where("Subject_subject_no='$Subject_subject_no' AND StudentSection_Student_student_no='$StudentSection_Student_student_no' AND StudentSection_Section_section_no='$StudentSection_Section_section_no'");
    if($result = $dbh_subjectstudentsection->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);
        $orig_Subject_subject_no = $Subject_subject_no;
        $orig_StudentSection_Student_student_no = $StudentSection_Student_student_no;
        $orig_StudentSection_Section_section_no = $StudentSection_Section_section_no;

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_subjectstudentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    if($_POST['submit'])
    {
        log_action('Pressed submit button', $_SERVER[PHP_SELF]);


        require_once 'validation_class.php';
        require_once 'subclasses/subjectstudentsection.php';
        $dbh_subjectstudentsection = new subjectstudentsection;
        $validator = new validation;

        $message .= $dbh_subjectstudentsection->sanitize($_POST);
        extract($_POST);

        if($dbh_subjectstudentsection->check_uniqueness_for_editing($_POST)) ;
        else $message = "Record already exists with the same primary identifiers!";

        if($message=="")
        {
            $dbh_subjectstudentsection->edit($_POST);


            header("location: listview_subjectstudentsection.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
        }
    }
}
require_once 'subclasses/subjectstudentsection_html.php';
$html = new subjectstudentsection_html;
$html->draw_header('Edit subjectstudentsection', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);

echo "<input type=hidden name='orig_Subject_subject_no' value='$orig_Subject_subject_no'>";
echo "<input type=hidden name='orig_StudentSection_Student_student_no' value='$orig_StudentSection_Student_student_no'>";
echo "<input type=hidden name='orig_StudentSection_Section_section_no' value='$orig_StudentSection_Section_section_no'>";

$html->draw_controls('edit');

$html->draw_footer();