<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('Edit teacher');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

if(isset($_GET['teacher_no']) && isset($_GET['Department_dept_no']))
{
    extract($_GET);

    $page_from = htmlentities($_GET['page_from']);
    $filter_used = htmlentities($_GET['filter_used']);
    $filter_field_used = htmlentities($_GET['filter_field_used']);

    require_once 'subclasses/teacher.php';
    $dbh_teacher = new teacher;
    $dbh_teacher->set_where("teacher_no='$teacher_no' AND Department_dept_no='$Department_dept_no'");
    if($result = $dbh_teacher->make_query())
    {
        $data = $result->fetch_assoc();
        extract($data);
        $orig_Department_dept_no = $Department_dept_no;

    }


}
elseif(xsrf_guard())
{
    extract($_POST);
    if($_POST['cancel']) 
    {
        log_action('Pressed cancel button', $_SERVER[PHP_SELF]);
        header("location: listview_teacher.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
    }

    if($_POST['submit'])
    {
        log_action('Pressed submit button', $_SERVER[PHP_SELF]);


        require_once 'validation_class.php';
        require_once 'subclasses/teacher.php';
        $dbh_teacher = new teacher;
        $validator = new validation;

        $message .= $dbh_teacher->sanitize($_POST);
        extract($_POST);

        if($dbh_teacher->check_uniqueness_for_editing($_POST)) ;
        else $message = "Record already exists with the same primary identifiers!";

        if($message=="")
        {
            $dbh_teacher->edit($_POST);


            header("location: listview_teacher.php?filter_field=$filter_field_used&filter=$filter_used&page_from=$page_from");
        }
    }
}
require_once 'subclasses/teacher_html.php';
$html = new teacher_html;
$html->draw_header('Edit teacher', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from);
echo "<input type=hidden name='teacher_no' value='$teacher_no'>";
echo "<input type=hidden name='orig_Department_dept_no' value='$orig_Department_dept_no'>";

$html->draw_controls('edit');

$html->draw_footer();