<?php
//******************************************************************
//This file was generated by Cobalt, a rapid application development 
//framework developed by JV Roig (jvroig@jvroig.com).
//
//Cobalt on the web: http://cobalt.jvroig.com
//******************************************************************
require_once 'path.php';
init_cobalt('ALLOW_ALL');
if(!isset($_POST['form_key'])) log_action("Module Access", $_SERVER['PHP_SELF']);

header('location: ' . INDEX_TARGET);